# .github/workflows/deploy.yml
#

name: Deploy Website

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # or your preferred region

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 4: Build step (if you have any build requirements)
      - name: Build website
        run: |
          echo "next step"

      # Step 5: Deploy infrastructure
      - name: Deploy infrastructure
        working-directory: ./infrastructure
        run: |
          terraform init
          terraform apply -auto-approve

      # Step 6: Sync website files to S3
      - name: Sync files to S3
        run: |
            aws s3 sync ./website s3://personal-resume-website-tatofs